# Blog info
blog_name: Hades
slogan: 程序猿何大叔
url: https://ironmaxi.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.png

# Set favicon
favicon: /images/favicon.ico

# For seo
keywords: 程序猿何大叔,Hades,前端,前端开发,用户体验,设计,frontend,design,nodejs,JavaScript

startyear: 2017

home_nav:
  # - name: 文章
  #   url: /articles
  #   target_blank: false
  - name: 归档
    url: /archives
    target_blank: false
  # - name: 分类
  #   url: /categories
  #   target_blank: false
  - name: 关于
    url: /about
    target_blank: false
  - name: GITHUB
    url: https://github.com/ironmaxtory
    target_blank: true

# config page nav
page_nav:
  - name: 主页
    url: /
    target_blank: false # 不在新页面打开
  - name: 归档
    url: /archives
    target_blank: false
  # - name: 分类
  #   url: /categories
  #   target_blank: false
  # - name: 标签
  #   url: /tags/
  #   target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
#  - name: RSS
#    url: /atom.xml
#    target_blank: true # 在新页面打开


# baidu_analytics: 53c703098249d2138b0244cbcb1a756f

# disqus_shortname: hades
